//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mezeo.Resources.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mezeo.Resources.en.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of the sync application is now available..
        /// </summary>
        internal static string AppAvailableMessage {
            get {
                return ResourceManager.GetString("AppAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is offline.
        /// </summary>
        internal static string AppOfflineMenu {
            get {
                return ResourceManager.GetString("AppOfflineMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $$PRODUCT$$ Setup.
        /// </summary>
        internal static string CaptionFileMissingDialog {
            get {
                return ResourceManager.GetString("CaptionFileMissingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckforUpdate {
            get {
                return ResourceManager.GetString("CheckforUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;No&quot; to exit the application and then re-run the application after you have returned the folder to its expected location.  The application will resume automatic syncing with your online account..
        /// </summary>
        internal static string ClickNoExit {
            get {
                return ResourceManager.GetString("ClickNoExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; if you want to create a new sync folder and restore files from your online account.  Automatic sync will resume once your files are downloaded..
        /// </summary>
        internal static string ClickYesRestore {
            get {
                return ResourceManager.GetString("ClickYesRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detected.
        /// </summary>
        internal static string ConflictDetectedError {
            get {
                return ResourceManager.GetString("ConflictDetectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Detected.
        /// </summary>
        internal static string ConflictDetectedModified {
            get {
                return ResourceManager.GetString("ConflictDetectedModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is great!    All your files are in sync and there are no conflicts or errors to report at this time..
        /// </summary>
        internal static string ConflictResolveText {
            get {
                return ResourceManager.GetString("ConflictResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conflict was detected while updating the file. This typically happens when you make a change to a file in your local sync folder and the corresponding file on the server .
        /// </summary>
        internal static string ErrorBlurbConflict1 {
            get {
                return ResourceManager.GetString("ErrorBlurbConflict1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was updated between sync cycles, from another source..
        /// </summary>
        internal static string ErrorBlurbConflict2 {
            get {
                return ResourceManager.GetString("ErrorBlurbConflict2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local changes have been saved as the most recent version..
        /// </summary>
        internal static string ErrorBlurbConflict3 {
            get {
                return ResourceManager.GetString("ErrorBlurbConflict3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see all versions of the file from the web app, .
        /// </summary>
        internal static string ErrorBlurbConflict4 {
            get {
                return ResourceManager.GetString("ErrorBlurbConflict4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by clicking the link to the &apos;Server File Info&apos; below..
        /// </summary>
        internal static string ErrorBlurbConflict5 {
            get {
                return ResourceManager.GetString("ErrorBlurbConflict5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync manager was unable to download the file from your .
        /// </summary>
        internal static string ErrorBlurbDownload1 {
            get {
                return ResourceManager.GetString("ErrorBlurbDownload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account to your local machine..
        /// </summary>
        internal static string ErrorBlurbDownload2 {
            get {
                return ResourceManager.GetString("ErrorBlurbDownload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is typically caused by internet or service interruptions and is usually resolved automatically. Another download attempt will be made during the next sync cycle..
        /// </summary>
        internal static string ErrorBlurbDownload3 {
            get {
                return ResourceManager.GetString("ErrorBlurbDownload3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync manager was unable to upload the file from your local machine to your .
        /// </summary>
        internal static string ErrorBlurbUpload1 {
            get {
                return ResourceManager.GetString("ErrorBlurbUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account..
        /// </summary>
        internal static string ErrorBlurbUpload2 {
            get {
                return ResourceManager.GetString("ErrorBlurbUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is typically caused by internet or service interruptions and is usually resolved automatically.  Another upload attempt will be made during the next sync cycle..
        /// </summary>
        internal static string ErrorBlurbUpload3 {
            get {
                return ResourceManager.GetString("ErrorBlurbUpload3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is evaluating local changes..
        /// </summary>
        internal static string EvaluatingLocalChanges {
            get {
                return ResourceManager.GetString("EvaluatingLocalChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitSyncManager {
            get {
                return ResourceManager.GetString("ExitSyncManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your $$PRODUCT$$ folder was not found in its expected location:.
        /// </summary>
        internal static string ExpectedLocation {
            get {
                return ResourceManager.GetString("ExpectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder may have been moved, renamed, or deleted..
        /// </summary>
        internal static string FolderMoved {
            get {
                return ResourceManager.GetString("FolderMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update .
        /// </summary>
        internal static string InstallUpdateText {
            get {
                return ResourceManager.GetString("InstallUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space available to download file(s)..
        /// </summary>
        internal static string InsufficientStorageMessage {
            get {
                return ResourceManager.GetString("InsufficientStorageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        internal static string IssuesDateAndTimeColumn {
            get {
                return ResourceManager.GetString("IssuesDateAndTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        internal static string IssuesEventViewerButtonText {
            get {
                return ResourceManager.GetString("IssuesEventViewerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Info:.
        /// </summary>
        internal static string IssuesFileInfoLabel {
            get {
                return ResourceManager.GetString("IssuesFileInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Sync Issues.
        /// </summary>
        internal static string IssuesHeader {
            get {
                return ResourceManager.GetString("IssuesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Conflict.
        /// </summary>
        internal static string IssuesIgnoreConflictButtonText {
            get {
                return ResourceManager.GetString("IssuesIgnoreConflictButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string IssuesIssueColumnText {
            get {
                return ResourceManager.GetString("IssuesIssueColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local File:.
        /// </summary>
        internal static string IssuesLocalFileLabel {
            get {
                return ResourceManager.GetString("IssuesLocalFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified:.
        /// </summary>
        internal static string IssuesModifiedLabel {
            get {
                return ResourceManager.GetString("IssuesModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string IssuesNameColumnText {
            get {
                return ResourceManager.GetString("IssuesNameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string IssuesSizeLabel {
            get {
                return ResourceManager.GetString("IssuesSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string IssuesTitle {
            get {
                return ResourceManager.GetString("IssuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password you entered is incorrect..
        /// </summary>
        internal static string LoginErrorText {
            get {
                return ResourceManager.GetString("LoginErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Login.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest access not allowed.
        /// </summary>
        internal static string LoginGuestAccMsgText {
            get {
                return ResourceManager.GetString("LoginGuestAccMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sync is currently in progress..
        /// </summary>
        internal static string MezeoExitString1 {
            get {
                return ResourceManager.GetString("MezeoExitString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel sync and close $$PRODUCT$$ now?.
        /// </summary>
        internal static string MezeoExitString2 {
            get {
                return ResourceManager.GetString("MezeoExitString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found.  You have the latest version..
        /// </summary>
        internal static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordCueText {
            get {
                return ResourceManager.GetString("PasswordCueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Sync.
        /// </summary>
        internal static string PauseSync {
            get {
                return ResourceManager.GetString("PauseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string ProgressBarComplete {
            get {
                return ResourceManager.GetString("ProgressBarComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to resume sync operations .
        /// </summary>
        internal static string ResumeSyncOprationText {
            get {
                return ResourceManager.GetString("ResumeSyncOprationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Sync.
        /// </summary>
        internal static string ResumeSyncText {
            get {
                return ResourceManager.GetString("ResumeSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues found. Launch Sync Manager to review..
        /// </summary>
        internal static string SyncIssueFoundText {
            get {
                return ResourceManager.GetString("SyncIssueFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Manager.
        /// </summary>
        internal static string SyncManager {
            get {
                return ResourceManager.GetString("SyncManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SyncManagerAboutLinkText {
            get {
                return ResourceManager.GetString("SyncManagerAboutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account files are downloading now.  Still collecting data ....
        /// </summary>
        internal static string SyncManagerAnalyseMessage1 {
            get {
                return ResourceManager.GetString("SyncManagerAnalyseMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress will be shown after all account data is collected.
        /// </summary>
        internal static string SyncManagerAnalyseMessage2 {
            get {
                return ResourceManager.GetString("SyncManagerAnalyseMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start working from your sync folder now..
        /// </summary>
        internal static string SyncManagerAnalyseMessage3 {
            get {
                return ResourceManager.GetString("SyncManagerAnalyseMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking server for updates....
        /// </summary>
        internal static string SyncManagerCheckingServer {
            get {
                return ResourceManager.GetString("SyncManagerCheckingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string SyncManagerDownloading {
            get {
                return ResourceManager.GetString("SyncManagerDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Sync:.
        /// </summary>
        internal static string SyncManagerFileSyncLabel {
            get {
                return ResourceManager.GetString("SyncManagerFileSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Folder.
        /// </summary>
        internal static string SyncManagerFolderLabel {
            get {
                return ResourceManager.GetString("SyncManagerFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SyncManagerHelpLinkText {
            get {
                return ResourceManager.GetString("SyncManagerHelpLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues Found.
        /// </summary>
        internal static string SyncManagerIssueFoundButtonText {
            get {
                return ResourceManager.GetString("SyncManagerIssueFoundButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync.
        /// </summary>
        internal static string SyncManagerLastSync {
            get {
                return ResourceManager.GetString("SyncManagerLastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Issues Found.
        /// </summary>
        internal static string SyncManagerMenuIssueFoundText {
            get {
                return ResourceManager.GetString("SyncManagerMenuIssueFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Folder.
        /// </summary>
        internal static string SyncManagerMoveFolderButtonText {
            get {
                return ResourceManager.GetString("SyncManagerMoveFolderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SyncManagerOffButtonText {
            get {
                return ResourceManager.GetString("SyncManagerOffButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string SyncManagerOnButtonText {
            get {
                return ResourceManager.GetString("SyncManagerOnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn sync &apos;On&apos; to resume.
        /// </summary>
        internal static string SyncManagerResumeSync {
            get {
                return ResourceManager.GetString("SyncManagerResumeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files in sync.
        /// </summary>
        internal static string SyncManagerStatusAllFilesInSyncLabel {
            get {
                return ResourceManager.GetString("SyncManagerStatusAllFilesInSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SyncManagerStatusLabel {
            get {
                return ResourceManager.GetString("SyncManagerStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync.
        /// </summary>
        internal static string SyncManagerStatusLastSyncLabel {
            get {
                return ResourceManager.GetString("SyncManagerStatusLastSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sync at.
        /// </summary>
        internal static string SyncManagerStatusNextSyncAtLabel {
            get {
                return ResourceManager.GetString("SyncManagerStatusNextSyncAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is disabled.
        /// </summary>
        internal static string SyncManagerSyncDisabled {
            get {
                return ResourceManager.GetString("SyncManagerSyncDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Now.
        /// </summary>
        internal static string SyncManagerSyncNowButtonText {
            get {
                return ResourceManager.GetString("SyncManagerSyncNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files in sync.
        /// </summary>
        internal static string SyncManagerSyncStatus {
            get {
                return ResourceManager.GetString("SyncManagerSyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sync.
        /// </summary>
        internal static string SyncManagerSyncStopButtonText {
            get {
                return ResourceManager.GetString("SyncManagerSyncStopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable (click ON) from Sync Manager..
        /// </summary>
        internal static string SyncManagerTrayEnableOnText {
            get {
                return ResourceManager.GetString("SyncManagerTrayEnableOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string SyncManagerUsageLabel {
            get {
                return ResourceManager.GetString("SyncManagerUsageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string SyncManagerUsageOfLabel {
            get {
                return ResourceManager.GetString("SyncManagerUsageOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string SyncManagerUsageUnlimited {
            get {
                return ResourceManager.GetString("SyncManagerUsageUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string SyncManagerUsageUsed {
            get {
                return ResourceManager.GetString("SyncManagerUsageUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync in Progress.
        /// </summary>
        internal static string SyncProgress {
            get {
                return ResourceManager.GetString("SyncProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is starting up.
        /// </summary>
        internal static string SyncStartMessage {
            get {
                return ResourceManager.GetString("SyncStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is offline because it cannot connect to your account..
        /// </summary>
        internal static string TrayAppOfflineText {
            get {
                return ResourceManager.GetString("TrayAppOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync has found a connection and is online again..
        /// </summary>
        internal static string TrayAppOnlineText {
            get {
                return ResourceManager.GetString("TrayAppOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your files are up-to-date..
        /// </summary>
        internal static string TrayBalloonInitialSyncFilesUpToDateText {
            get {
                return ResourceManager.GetString("TrayBalloonInitialSyncFilesUpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sync folder is being updated with files from your account..
        /// </summary>
        internal static string TrayBalloonInitialSyncStartedText {
            get {
                return ResourceManager.GetString("TrayBalloonInitialSyncStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Sync Started.
        /// </summary>
        internal static string TrayBalloonInitialSyncStartedTitleText {
            get {
                return ResourceManager.GetString("TrayBalloonInitialSyncStartedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Sync Completed..
        /// </summary>
        internal static string TrayBalloonInitialSyncText {
            get {
                return ResourceManager.GetString("TrayBalloonInitialSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sync folder is up-to-date..
        /// </summary>
        internal static string TrayBalloonSyncFolderUpToDate {
            get {
                return ResourceManager.GetString("TrayBalloonSyncFolderUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync has been paused.
        /// </summary>
        internal static string TrayBalloonSyncPauseText {
            get {
                return ResourceManager.GetString("TrayBalloonSyncPauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync has been resumed..
        /// </summary>
        internal static string TrayBalloonSyncResumeText {
            get {
                return ResourceManager.GetString("TrayBalloonSyncResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Status.
        /// </summary>
        internal static string TrayBalloonSyncStatusText {
            get {
                return ResourceManager.GetString("TrayBalloonSyncStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Stopped.
        /// </summary>
        internal static string TrayBalloonSyncStopText {
            get {
                return ResourceManager.GetString("TrayBalloonSyncStopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync is Up-to-date.
        /// </summary>
        internal static string TrayHoverInitialSyncUpToDateText {
            get {
                return ResourceManager.GetString("TrayHoverInitialSyncUpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % complete.
        /// </summary>
        internal static string TrayHoverSyncProgressInitialText {
            get {
                return ResourceManager.GetString("TrayHoverSyncProgressInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sync in progress....
        /// </summary>
        internal static string TrayHoverSyncProgressText {
            get {
                return ResourceManager.GetString("TrayHoverSyncProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string UsageNotAvailable {
            get {
                return ResourceManager.GetString("UsageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserIdCueText {
            get {
                return ResourceManager.GetString("UserIdCueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Website.
        /// </summary>
        internal static string WebsiteUrl {
            get {
                return ResourceManager.GetString("WebsiteUrl", resourceCulture);
            }
        }
    }
}
